#!/usr/bin/env python3
"""
HW5 Part 3 item 1 - generate the tool-contract documentation.

The spec: "Using the same three domain tools and the same rejected-call
examples you captured in Part 2B, write down expected JSON input schema, the
rejected JSON input, and the returned error output for each call. Documents
why each Part 2B call was rejected."

Rather than hand-writing that table into the report, this script produces it
from the running code:

    * the input schema is read from the MCP tool definition itself -- the same
      JSON Schema the Inspector displayed in your Part 2B screenshots, so the
      document cannot drift from what the server actually advertises
    * the rejected input and its error output are produced by calling each
      tool with the invalid argument, so the error text in the document is
      the error text the tool really returns

The rejected inputs below are the same ones used in the Part 2B Inspector
screenshots. No new rejected calls are invented; this only records them.

Run (from the repo root):
    .venv/bin/python code/mcp_servers/tool_contracts.py

Writes reports/hw05/raw/tool_contracts.md.
"""

from __future__ import annotations

import asyncio
import json
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

logging.basicConfig(level=logging.WARNING, stream=sys.stderr)

REPO_ROOT = Path(__file__).resolve().parents[2]
RAW_DIR = REPO_ROOT / "reports" / "hw05" / "raw"

# (tool, valid input, rejected input, why it is rejected)
# These rejected inputs are exactly the Part 2B Inspector cases.
CASES = [
    (
        "search_incidents",
        {"query": "Downtown", "limit": 5},
        {"query": "Downtown", "limit": 0},
        "limit is outside the documented range 1-50. A page size of zero has "
        "no meaningful result, and leaving it unbounded would let one call ask "
        "for the whole table.",
    ),
    (
        "incident_details",
        {"incident_code": "INC-3170-00001"},
        {"incident_code": "INC-317-1"},
        "incident_code does not match INC-NNNN-NNNNN. The format is checked "
        "before any query runs, so a malformed code never reaches the "
        "database.",
    ),
    (
        "incident_stats",
        {"group_by": "agency"},
        {"group_by": "banana"},
        "group_by is not one of the three groupings the tool supports. It maps "
        "to a column name, so accepting arbitrary text would be both a wrong "
        "answer and an injection surface.",
    ),
]


def fence(obj) -> str:
    return "```json\n" + json.dumps(obj, indent=2) + "\n```"


async def build() -> str:
    import transit_server
    import transit_tools

    tools = {t.name: t for t in await transit_server.mcp.list_tools()}

    out: list[str] = []
    out.append("# HW5 Part 3 - Tool contracts under stress\n")
    out.append(
        "Generated by `code/mcp_servers/tool_contracts.py`. Input schemas are "
        "read from the live MCP tool definitions; error outputs are the actual "
        "return values of the rejected calls captured in Part 2B.\n"
    )
    out.append(
        "Every tool answers with the same envelope, `{ok, data, error}`, "
        "defined once in `code/mcp_servers/envelope.py` and reused by "
        "`execute_tool` in Part 4. A rejection is a value, not an exception: "
        "`ok` is false, `data` is null, and `error` carries the reason.\n"
    )

    for name, valid_input, bad_input, why in CASES:
        tool = tools[name]
        out.append(f"\n## `{name}`\n")
        out.append(f"{(tool.description or '').strip().splitlines()[0]}\n")

        out.append("### Expected JSON input schema\n")
        out.append(fence(tool.inputSchema) + "\n")

        out.append("### Accepted call\n")
        accepted = getattr(transit_tools, name)(**valid_input)
        out.append("Input:\n" + fence(valid_input) + "\n")
        out.append(
            f"Output: `ok: true`, `error: null`"
            f"{', ' + str(accepted['data'].get('count')) + ' results' if isinstance(accepted.get('data'), dict) and 'count' in accepted['data'] else ''}.\n"
        )

        out.append("### Rejected JSON input\n")
        out.append(fence(bad_input) + "\n")

        out.append("### Returned error output\n")
        rejected = getattr(transit_tools, name)(**bad_input)
        out.append(fence(rejected) + "\n")

        out.append("### Why it was rejected\n")
        out.append(why + "\n")

    out.append("\n## Summary\n")
    out.append("| Tool | Rejected input | Error returned |")
    out.append("|---|---|---|")
    for name, _valid, bad_input, _why in CASES:
        rejected = getattr(transit_tools, name)(**bad_input)
        compact = json.dumps(bad_input).replace("|", "\\|")
        message = (rejected["error"] or "").replace("|", "\\|")
        out.append(f"| `{name}` | `{compact}` | {message} |")
    out.append("")

    return "\n".join(out)


def main() -> None:
    text = asyncio.run(build())
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    path = RAW_DIR / "tool_contracts.md"
    path.write_text(text)
    print(f"wrote {path.relative_to(REPO_ROOT)}  ({len(text.splitlines())} lines)")
    print("\nPaste the summary table into the report; the full file is the "
          "supporting evidence in reports/hw05/raw/.")


if __name__ == "__main__":
    main()
